// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Platform.Infrastructure.Data;

#nullable disable

namespace Platform.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260506131009_AddParentTenantGuards")]
    partial class AddParentTenantGuards
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Platform.Domain.Auditing.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("actor_type");

                    b.Property<JsonDocument>("After")
                        .HasColumnType("jsonb")
                        .HasColumnName("after");

                    b.Property<JsonDocument>("Before")
                        .HasColumnType("jsonb")
                        .HasColumnName("before");

                    b.Property<string>("ChangeKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("change_kind");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id", "OccurredAt")
                        .HasName("pk_audit_event");

                    b.HasIndex("TenantId", "OccurredAt")
                        .HasDatabaseName("ix_audit_event_tenant_id_occurred_at");

                    b.HasIndex("EntityType", "EntityId", "OccurredAt")
                        .HasDatabaseName("ix_audit_event_entity_type_entity_id_occurred_at");

                    b.ToTable("audit_event", (string)null);
                });

            modelBuilder.Entity("Platform.Domain.Auth.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code");

                    b.HasKey("Id")
                        .HasName("pk_permission");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_permission_code");

                    b.ToTable("permission", (string)null);
                });

            modelBuilder.Entity("Platform.Domain.Auth.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_role_global_code")
                        .HasFilter("tenant_id IS NULL");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_role_tenant_id_code")
                        .HasFilter("tenant_id IS NOT NULL");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("Platform.Domain.Auth.RoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid?>("GrantedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid?>("ScopeId")
                        .HasColumnType("uuid")
                        .HasColumnName("scope_id");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("scope_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_role_assignment");

                    b.HasIndex("GrantedBy")
                        .HasDatabaseName("ix_role_assignment_granted_by");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_assignment_role_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_role_assignment_tenant_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_role_assignment_user_id");

                    b.ToTable("role_assignment", null, t =>
                        {
                            t.HasCheckConstraint("ck_role_assignment_scope", "(scope_type = 'tenant' AND scope_id IS NULL)\nOR (scope_type IN ('workspace', 'campaign', 'campaign_series') AND scope_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Platform.Domain.Auth.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permission");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permission_permission_id");

                    b.ToTable("role_permission", (string)null);
                });

            modelBuilder.Entity("Platform.Domain.Auth.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_attempts");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("locale");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<string>("MfaSecret")
                        .HasColumnType("text")
                        .HasColumnName("mfa_secret");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_user_account");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_account_tenant_id_email");

                    b.ToTable("user_account", (string)null);
                });

            modelBuilder.Entity("Platform.Domain.Instruments.Instrument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CanonicalTemplateVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("canonical_template_version_id");

                    b.Property<string>("CitationApa")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("citation_apa");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code");

                    b.Property<string>("ConstructCategory")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("construct_category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.PrimitiveCollection<string[]>("Developers")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("developers");

                    b.Property<string>("Doi")
                        .HasColumnType("text")
                        .HasColumnName("doi");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("domain");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_global");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_locked");

                    b.Property<DateTimeOffset?>("LicenseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("license_expires_at");

                    b.Property<string>("LicenseTermsUrl")
                        .HasColumnType("text")
                        .HasColumnName("license_terms_url");

                    b.Property<string>("LicenseType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("license_type");

                    b.Property<Guid?>("ParentInstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_instrument_id");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValidityStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("validity_status");

                    b.Property<string>("Vendor")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("vendor");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version");

                    b.Property<int?>("YearFirstPublished")
                        .HasColumnType("integer")
                        .HasColumnName("year_first_published");

                    b.HasKey("Id")
                        .HasName("pk_instrument");

                    b.HasIndex("ParentInstrumentId")
                        .HasDatabaseName("ix_instrument_parent_instrument_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_instrument_tenant_id");

                    b.HasIndex("Code", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_instrument_global_code_version")
                        .HasFilter("tenant_id IS NULL");

                    b.HasIndex("TenantId", "Code", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_instrument_tenant_id_code_version")
                        .HasFilter("tenant_id IS NOT NULL");

                    b.ToTable("instrument", null, t =>
                        {
                            t.HasCheckConstraint("ck_instrument_canonical_parent_shape", "validity_status <> 'canonical' OR parent_instrument_id IS NULL");

                            t.HasCheckConstraint("ck_instrument_derived_parent_shape", "validity_status <> 'derived' OR (tenant_id IS NOT NULL AND parent_instrument_id IS NOT NULL AND is_global = FALSE)");

                            t.HasCheckConstraint("ck_instrument_domain", "domain IN ('psychometric','ergonomic','medical','educational','regulatory','other')");

                            t.HasCheckConstraint("ck_instrument_global_tenant_shape", "(is_global = TRUE AND tenant_id IS NULL) OR (is_global = FALSE AND tenant_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_instrument_license_type", "license_type IN ('free','free_academic','paid','unknown')");

                            t.HasCheckConstraint("ck_instrument_validity_status", "validity_status IN ('canonical','derived','draft','retired')");
                        });
                });

            modelBuilder.Entity("Platform.Domain.Instruments.InstrumentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<Guid?>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<bool>("ReverseCoded")
                        .HasColumnType("boolean")
                        .HasColumnName("reverse_coded");

                    b.Property<string>("SubscaleCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("subscale_code");

                    b.HasKey("Id")
                        .HasName("pk_instrument_item");

                    b.HasIndex("InstrumentId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_instrument_item_instrument_id_code");

                    b.HasIndex("InstrumentId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ix_instrument_item_instrument_id_ordinal");

                    b.ToTable("instrument_item", null, t =>
                        {
                            t.HasCheckConstraint("ck_instrument_item_ordinal_positive", "ordinal > 0");
                        });
                });

            modelBuilder.Entity("Platform.Domain.Instruments.InstrumentNorm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("locale");

                    b.Property<decimal?>("Mean")
                        .HasPrecision(8, 3)
                        .HasColumnType("numeric(8,3)")
                        .HasColumnName("mean");

                    b.Property<string>("NormType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("norm_type");

                    b.Property<string>("Percentiles")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("percentiles");

                    b.Property<string>("Population")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("population");

                    b.Property<int>("SampleSize")
                        .HasColumnType("integer")
                        .HasColumnName("sample_size");

                    b.Property<string>("SourceCitation")
                        .HasColumnType("text")
                        .HasColumnName("source_citation");

                    b.Property<int?>("SourceYear")
                        .HasColumnType("integer")
                        .HasColumnName("source_year");

                    b.Property<decimal?>("StandardDeviation")
                        .HasPrecision(8, 3)
                        .HasColumnType("numeric(8,3)")
                        .HasColumnName("sd");

                    b.Property<string>("SubscaleCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("subscale_code");

                    b.HasKey("Id")
                        .HasName("pk_instrument_norm");

                    b.HasIndex("InstrumentId", "SubscaleCode", "Locale", "NormType")
                        .HasDatabaseName("ix_instrument_norm_lookup");

                    b.ToTable("instrument_norm", null, t =>
                        {
                            t.HasCheckConstraint("ck_instrument_norm_sample_size_positive", "sample_size > 0");

                            t.HasCheckConstraint("ck_instrument_norm_type", "norm_type IN ('published_instrument','platform_benchmark','tenant_benchmark')");
                        });
                });

            modelBuilder.Entity("Platform.Domain.Instruments.InstrumentSubscale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<int>("ItemCount")
                        .HasColumnType("integer")
                        .HasColumnName("item_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<decimal?>("ReliabilityAlphaPublished")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("reliability_alpha_published");

                    b.Property<string>("ScoringMethod")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("scoring_method");

                    b.HasKey("Id")
                        .HasName("pk_instrument_subscale");

                    b.HasIndex("InstrumentId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_instrument_subscale_instrument_id_code");

                    b.ToTable("instrument_subscale", null, t =>
                        {
                            t.HasCheckConstraint("ck_instrument_subscale_item_count_positive", "item_count > 0");

                            t.HasCheckConstraint("ck_instrument_subscale_reliability_alpha_range", "reliability_alpha_published IS NULL OR (reliability_alpha_published >= 0 AND reliability_alpha_published <= 1)");

                            t.HasCheckConstraint("ck_instrument_subscale_scoring_method", "scoring_method IN ('mean','sum','weighted')");
                        });
                });

            modelBuilder.Entity("Platform.Domain.Instruments.InstrumentTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("field");

                    b.Property<Guid?>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<Guid?>("InstrumentItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_item_id");

                    b.Property<Guid?>("InstrumentSubscaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_subscale_id");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("locale");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("translation_workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_translation");

                    b.HasIndex("InstrumentId", "Field", "Locale")
                        .IsUnique()
                        .HasDatabaseName("ix_translation_unique_instrument")
                        .HasFilter("instrument_id IS NOT NULL");

                    b.HasIndex("InstrumentItemId", "Field", "Locale")
                        .IsUnique()
                        .HasDatabaseName("ix_translation_unique_instrument_item")
                        .HasFilter("instrument_item_id IS NOT NULL");

                    b.HasIndex("InstrumentSubscaleId", "Field", "Locale")
                        .IsUnique()
                        .HasDatabaseName("ix_translation_unique_instrument_subscale")
                        .HasFilter("instrument_subscale_id IS NOT NULL");

                    b.ToTable("translation", null, t =>
                        {
                            t.HasCheckConstraint("ck_translation_exactly_one_instrument_target", "((instrument_id IS NOT NULL)::int\n+ (instrument_subscale_id IS NOT NULL)::int\n+ (instrument_item_id IS NOT NULL)::int) = 1");

                            t.HasCheckConstraint("ck_translation_status", "status IN ('draft_translation','back_translated','reconciled','approved_canonical_equivalent','approved_derivative','rejected')");
                        });
                });

            modelBuilder.Entity("Platform.Domain.Outbox.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("aggregate_type");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_at");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_outbox_event");

                    b.HasIndex("NextRetryAt")
                        .HasDatabaseName("ix_outbox_event_unpublished_next_retry_at")
                        .HasFilter("published_at IS NULL");

                    b.HasIndex("AggregateId", "CreatedAt")
                        .HasDatabaseName("ix_outbox_event_aggregate_id_created_at");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("ix_outbox_event_tenant_id_created_at");

                    b.ToTable("outbox_event", (string)null);
                });

            modelBuilder.Entity("Platform.Domain.Subjects.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_id");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("locale");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_account_id");

                    b.Property<Guid?>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_subject");

                    b.HasIndex("Attributes")
                        .HasDatabaseName("ix_subject_attributes_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Attributes"), "gin");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_subject_tenant_id");

                    b.HasIndex("UserAccountId")
                        .HasDatabaseName("ix_subject_user_account_id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_subject_tenant_id_email")
                        .HasFilter("email IS NOT NULL");

                    b.HasIndex("TenantId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_subject_tenant_id_external_id")
                        .HasFilter("external_id IS NOT NULL");

                    b.ToTable("subject", (string)null);
                });

            modelBuilder.Entity("Platform.Domain.Subjects.SubjectGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_group_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_subject_group");

                    b.HasAlternateKey("Id", "TenantId")
                        .HasName("ak_subject_group_id_tenant_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_subject_group_tenant_id");

                    b.HasIndex("ParentGroupId", "TenantId")
                        .HasDatabaseName("ix_subject_group_parent_group_id_tenant_id");

                    b.ToTable("subject_group", (string)null);
                });

            modelBuilder.Entity("Platform.Domain.Subjects.SubjectMembership", b =>
                {
                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("RoleInGroup")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role_in_group");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.HasKey("SubjectId", "GroupId")
                        .HasName("pk_subject_membership");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_subject_membership_group_id");

                    b.ToTable("subject_membership", null, t =>
                        {
                            t.HasCheckConstraint("ck_subject_membership_valid_range", "valid_from IS NULL OR valid_to IS NULL OR valid_to >= valid_from");
                        });
                });

            modelBuilder.Entity("Platform.Domain.Subjects.SubjectRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("RelatedSubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_subject_id");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("rel_type");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_subject_relationship");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_subject_relationship_tenant_id");

                    b.HasIndex("RelatedSubjectId", "RelationshipType")
                        .HasDatabaseName("ix_subject_relationship_related_subject_id_rel_type");

                    b.HasIndex("SubjectId", "RelationshipType")
                        .HasDatabaseName("ix_subject_relationship_subject_id_rel_type");

                    b.ToTable("subject_relationship", null, t =>
                        {
                            t.HasCheckConstraint("ck_subject_relationship_not_self_unless_self_type", "(subject_id <> related_subject_id AND rel_type <> 'self') OR (subject_id = related_subject_id AND rel_type = 'self')");

                            t.HasCheckConstraint("ck_subject_relationship_valid_range", "valid_from IS NULL OR valid_to IS NULL OR valid_to >= valid_from");
                        });
                });

            modelBuilder.Entity("Platform.Domain.Tenancy.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultLocale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("default_locale");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("region");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tenant");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_slug");

                    b.ToTable("tenant", (string)null);
                });

            modelBuilder.Entity("Platform.Domain.Auth.Role", b =>
                {
                    b.HasOne("Platform.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_role_tenant_tenant_id");
                });

            modelBuilder.Entity("Platform.Domain.Auth.RoleAssignment", b =>
                {
                    b.HasOne("Platform.Domain.Auth.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("GrantedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_role_assignment_user_account_granted_by");

                    b.HasOne("Platform.Domain.Auth.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_role_assignment_role_role_id");

                    b.HasOne("Platform.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_role_assignment_tenant_tenant_id");

                    b.HasOne("Platform.Domain.Auth.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_role_assignment_user_account_user_id");
                });

            modelBuilder.Entity("Platform.Domain.Auth.RolePermission", b =>
                {
                    b.HasOne("Platform.Domain.Auth.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permission_permission_permission_id");

                    b.HasOne("Platform.Domain.Auth.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permission_role_role_id");
                });

            modelBuilder.Entity("Platform.Domain.Auth.UserAccount", b =>
                {
                    b.HasOne("Platform.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_account_tenant_tenant_id");
                });

            modelBuilder.Entity("Platform.Domain.Instruments.Instrument", b =>
                {
                    b.HasOne("Platform.Domain.Instruments.Instrument", null)
                        .WithMany()
                        .HasForeignKey("ParentInstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_instrument_instrument_parent_instrument_id");

                    b.HasOne("Platform.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_instrument_tenant_tenant_id");
                });

            modelBuilder.Entity("Platform.Domain.Instruments.InstrumentItem", b =>
                {
                    b.HasOne("Platform.Domain.Instruments.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_instrument_item_instrument_instrument_id");
                });

            modelBuilder.Entity("Platform.Domain.Instruments.InstrumentNorm", b =>
                {
                    b.HasOne("Platform.Domain.Instruments.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_instrument_norm_instrument_instrument_id");
                });

            modelBuilder.Entity("Platform.Domain.Instruments.InstrumentSubscale", b =>
                {
                    b.HasOne("Platform.Domain.Instruments.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_instrument_subscale_instrument_instrument_id");
                });

            modelBuilder.Entity("Platform.Domain.Instruments.InstrumentTranslation", b =>
                {
                    b.HasOne("Platform.Domain.Instruments.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_translation_instrument_instrument_id");

                    b.HasOne("Platform.Domain.Instruments.InstrumentItem", null)
                        .WithMany()
                        .HasForeignKey("InstrumentItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_translation_instrument_item_instrument_item_id");

                    b.HasOne("Platform.Domain.Instruments.InstrumentSubscale", null)
                        .WithMany()
                        .HasForeignKey("InstrumentSubscaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_translation_instrument_subscale_instrument_subscale_id");
                });

            modelBuilder.Entity("Platform.Domain.Subjects.Subject", b =>
                {
                    b.HasOne("Platform.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subject_tenant_tenant_id");

                    b.HasOne("Platform.Domain.Auth.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_subject_user_account_user_account_id");
                });

            modelBuilder.Entity("Platform.Domain.Subjects.SubjectGroup", b =>
                {
                    b.HasOne("Platform.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subject_group_tenant_tenant_id");

                    b.HasOne("Platform.Domain.Subjects.SubjectGroup", null)
                        .WithMany()
                        .HasForeignKey("ParentGroupId", "TenantId")
                        .HasPrincipalKey("Id", "TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_subject_group_subject_group_parent_group_id");
                });

            modelBuilder.Entity("Platform.Domain.Subjects.SubjectMembership", b =>
                {
                    b.HasOne("Platform.Domain.Subjects.SubjectGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subject_membership_subject_group_group_id");

                    b.HasOne("Platform.Domain.Subjects.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subject_membership_subject_subject_id");
                });

            modelBuilder.Entity("Platform.Domain.Subjects.SubjectRelationship", b =>
                {
                    b.HasOne("Platform.Domain.Subjects.Subject", null)
                        .WithMany()
                        .HasForeignKey("RelatedSubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subject_relationship_subject_related_subject_id");

                    b.HasOne("Platform.Domain.Subjects.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subject_relationship_subject_subject_id");

                    b.HasOne("Platform.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subject_relationship_tenant_tenant_id");
                });
#pragma warning restore 612, 618
        }
    }
}
